name: Build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: '21'
          cache: maven
      - run: |
          mvn -B package --file pom.xml
          cp target/bitwigrandomizer.jar target/bitwigrandomizer.bwextension
      - uses: actions/upload-artifact@v4
        with:
          name: bitwigrandomizer
          path: target/bitwigrandomizer.bwextension
      